apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: markenx-api
  namespace: monitoring
  labels:
    release: monitoring-stack
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  namespaceSelector:
    matchNames:
      - markenx

  selector:
    matchLabels:
      app: markenx-api

  endpoints:
    - port: http
      path: /api/v1/actuator/prometheus
      interval: 15s
