apiVersion: v1
kind: Namespace
metadata:
  name: trivy
  labels:
    name: trivy
    component: security-scanning
    team: devops-security
  annotations:
    description: "Namespace para el Trivy Operator y recursos relacionados"
spec:
  finalizers:
    - kubernetes