apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: trivy
  labels:
    app: trivy-operator
    component: controller
automountServiceAccountToken: true  # Permite al Pod autenticarse con la API