apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MarkenX/markenx-config.git
    targetRevision: main
    path: k8s/base/argocd/crds/prometheus-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: null
