apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  annotations:
    # Deploy Trivy first so it can scan other applications as they deploy
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://github.com/MarkenX/markenx-config.git
    targetRevision: main
    path: k8s/base/trivy

  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
